host_ip = "192.168.1.1"
extra_ssh_args = ["-C"]
# Arguments need to be separated by a comma, see the example below
extra_wsl_args = ["--cd", "~"]

[[distribution]]
name = "Ubuntu"

[[distribution]]
name = "Debian"
username = "locust"
port = 4444